<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.github.exabrial</groupId>
		<artifactId>java25-parent-pom</artifactId>
		<version>1</version>
	</parent>

	<groupId>com.github.exabrial.locksmith</groupId>
	<artifactId>locksmith-parent</artifactId>
	<version>1.0.2-SNAPSHOT</version>

	<packaging>pom</packaging>
	<description>Locksmith: Retrieve secrets from OS credential stores and set them as Maven project properties</description>
	<name>${project.artifactId}</name>

	<url>https://github.com/exabrial/locksmith</url>
	<scm>
		<connection>scm:git:ssh://git@github.com/exabrial/locksmith.git</connection>
		<developerConnection>scm:git:ssh://git@github.com/exabrial/locksmith.git</developerConnection>
		<url>https://github.com/exabrial/locksmith/tree/master</url>
		<tag>HEAD</tag>
	</scm>

	<licenses>
		<license>
			<name>EUPL-1.2</name>
			<url>https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt</url>
			<distribution>repo</distribution>
			<comments>European Union Public Licence v1.2</comments>
		</license>
	</licenses>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.github.exabrial.locksmith</groupId>
				<artifactId>locksmith</artifactId>
				<version>1.0.2-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.github.exabrial.locksmith</groupId>
					<artifactId>locksmith-maven-plugin</artifactId>
					<version>1.0.2-SNAPSHOT</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-gpg-plugin</artifactId>
					<configuration>
						<keyname>871638A21A7F2C38066471420306A354336B4F0D</keyname>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<modules>
		<!-- please maintain alphabetical order -->
		<module>locksmith</module>
		<module>locksmith-maven-extension</module>
		<module>locksmith-maven-plugin</module>
	</modules>
</project>
