// Generated by jextract

package com.github.exabrial.locksmith.macos;

import static java.lang.foreign.ValueLayout.JAVA_BYTE;

import java.lang.foreign.AddressLayout;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.GroupLayout;
import java.lang.foreign.Linker;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.PaddingLayout;
import java.lang.foreign.SequenceLayout;
import java.lang.foreign.StructLayout;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.util.Arrays;
import java.util.stream.Collectors;

public class MacSecurity {

	MacSecurity() {
		// Should not be called directly
	}

	static final Arena LIBRARY_ARENA = Arena.ofAuto();
	static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

	static void traceDowncall(String name, Object... args) {
		String traceArgs = Arrays.stream(args).map(Object::toString).collect(Collectors.joining(", "));
		System.out.printf("%s(%s)\n", name, traceArgs);
	}

	static MemorySegment findOrThrow(String symbol) {
		return SYMBOL_LOOKUP.find(symbol).orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
	}

	static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
		try {
			return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
		} catch (ReflectiveOperationException ex) {
			throw new AssertionError(ex);
		}
	}

	static MemoryLayout align(MemoryLayout layout, long align) {
		return switch (layout) {
			case PaddingLayout p -> p;
			case ValueLayout v -> v.withByteAlignment(align);
			case GroupLayout g -> {
				MemoryLayout[] alignedMembers = g.memberLayouts().stream().map(m -> align(m, align)).toArray(MemoryLayout[]::new);
				yield g instanceof StructLayout ? MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
			}
			case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
		};
	}

	static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("Security"), LIBRARY_ARENA)
			.or(SymbolLookup.libraryLookup(System.mapLibraryName("CoreFoundation"), LIBRARY_ARENA)).or(SymbolLookup.loaderLookup())
			.or(Linker.nativeLinker().defaultLookup());

	public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
	public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
	public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
	public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
	public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
	public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
	public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
	public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
			.withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
	public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;

	private static class kCFAllocatorDefault$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kCFAllocatorDefault").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFAllocatorRef kCFAllocatorDefault
	 * }
	 */
	public static AddressLayout kCFAllocatorDefault$layout() {
		return kCFAllocatorDefault$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFAllocatorRef kCFAllocatorDefault
	 * }
	 */
	public static MemorySegment kCFAllocatorDefault$segment() {
		return kCFAllocatorDefault$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFAllocatorRef kCFAllocatorDefault
	 * }
	 */
	public static MemorySegment kCFAllocatorDefault() {
		return kCFAllocatorDefault$constants.SEGMENT.get(kCFAllocatorDefault$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFAllocatorRef kCFAllocatorDefault
	 * }
	 */
	public static void kCFAllocatorDefault(MemorySegment varValue) {
		kCFAllocatorDefault$constants.SEGMENT.set(kCFAllocatorDefault$constants.LAYOUT, 0L, varValue);
	}

	private static class CFRelease {
		public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(MacSecurity.C_POINTER);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("CFRelease");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c : * extern void CFRelease(CFTypeRef cf)
	 * }
	 */
	public static FunctionDescriptor CFRelease$descriptor() {
		return CFRelease.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c : * extern void CFRelease(CFTypeRef cf)
	 * }
	 */
	public static MethodHandle CFRelease$handle() {
		return CFRelease.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c : * extern void CFRelease(CFTypeRef cf)
	 * }
	 */
	public static MemorySegment CFRelease$address() {
		return CFRelease.ADDR;
	}

	/**
	 * {@snippet lang = c : * extern void CFRelease(CFTypeRef cf)
	 * }
	 */
	public static void CFRelease(MemorySegment cf) {
		var mh$ = CFRelease.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("CFRelease", cf);
			}
			mh$.invokeExact(cf);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}

	private static class kCFTypeDictionaryKeyCallBacks$constants {
		public static final GroupLayout LAYOUT = CFDictionaryKeyCallBacks.layout();
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kCFTypeDictionaryKeyCallBacks")
				.reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFDictionaryKeyCallBacks kCFTypeDictionaryKeyCallBacks
	 * }
	 */
	public static GroupLayout kCFTypeDictionaryKeyCallBacks$layout() {
		return kCFTypeDictionaryKeyCallBacks$constants.LAYOUT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFDictionaryKeyCallBacks kCFTypeDictionaryKeyCallBacks
	 * }
	 */
	public static MemorySegment kCFTypeDictionaryKeyCallBacks() {
		return kCFTypeDictionaryKeyCallBacks$constants.SEGMENT;
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFDictionaryKeyCallBacks kCFTypeDictionaryKeyCallBacks
	 * }
	 */
	public static void kCFTypeDictionaryKeyCallBacks(MemorySegment varValue) {
		MemorySegment.copy(varValue, 0L, kCFTypeDictionaryKeyCallBacks$constants.SEGMENT, 0L,
				kCFTypeDictionaryKeyCallBacks$constants.LAYOUT.byteSize());
	}

	private static class kCFTypeDictionaryValueCallBacks$constants {
		public static final GroupLayout LAYOUT = CFDictionaryValueCallBacks.layout();
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kCFTypeDictionaryValueCallBacks")
				.reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFDictionaryValueCallBacks kCFTypeDictionaryValueCallBacks
	 * }
	 */
	public static GroupLayout kCFTypeDictionaryValueCallBacks$layout() {
		return kCFTypeDictionaryValueCallBacks$constants.LAYOUT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFDictionaryValueCallBacks kCFTypeDictionaryValueCallBacks
	 * }
	 */
	public static MemorySegment kCFTypeDictionaryValueCallBacks() {
		return kCFTypeDictionaryValueCallBacks$constants.SEGMENT;
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFDictionaryValueCallBacks kCFTypeDictionaryValueCallBacks
	 * }
	 */
	public static void kCFTypeDictionaryValueCallBacks(MemorySegment varValue) {
		MemorySegment.copy(varValue, 0L, kCFTypeDictionaryValueCallBacks$constants.SEGMENT, 0L,
				kCFTypeDictionaryValueCallBacks$constants.LAYOUT.byteSize());
	}

	private static class CFDictionaryCreate {
		public static final FunctionDescriptor DESC = FunctionDescriptor.of(MacSecurity.C_POINTER, MacSecurity.C_POINTER,
				MacSecurity.C_POINTER, MacSecurity.C_POINTER, MacSecurity.C_LONG, MacSecurity.C_POINTER, MacSecurity.C_POINTER);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("CFDictionaryCreate");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c
	 * : * extern CFDictionaryRef CFDictionaryCreate(CFAllocatorRef allocator, const void **keys, const void **values, CFIndex numValues, const CFDictionaryKeyCallBacks *keyCallBacks, const CFDictionaryValueCallBacks *valueCallBacks)
	 * }
	 */
	public static FunctionDescriptor CFDictionaryCreate$descriptor() {
		return CFDictionaryCreate.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c
	 * : * extern CFDictionaryRef CFDictionaryCreate(CFAllocatorRef allocator, const void **keys, const void **values, CFIndex numValues, const CFDictionaryKeyCallBacks *keyCallBacks, const CFDictionaryValueCallBacks *valueCallBacks)
	 * }
	 */
	public static MethodHandle CFDictionaryCreate$handle() {
		return CFDictionaryCreate.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c
	 * : * extern CFDictionaryRef CFDictionaryCreate(CFAllocatorRef allocator, const void **keys, const void **values, CFIndex numValues, const CFDictionaryKeyCallBacks *keyCallBacks, const CFDictionaryValueCallBacks *valueCallBacks)
	 * }
	 */
	public static MemorySegment CFDictionaryCreate$address() {
		return CFDictionaryCreate.ADDR;
	}

	/**
	 * {@snippet lang = c
	 * : * extern CFDictionaryRef CFDictionaryCreate(CFAllocatorRef allocator, const void **keys, const void **values, CFIndex numValues, const CFDictionaryKeyCallBacks *keyCallBacks, const CFDictionaryValueCallBacks *valueCallBacks)
	 * }
	 */
	public static MemorySegment CFDictionaryCreate(MemorySegment allocator, MemorySegment keys, MemorySegment values, long numValues,
			MemorySegment keyCallBacks, MemorySegment valueCallBacks) {
		var mh$ = CFDictionaryCreate.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("CFDictionaryCreate", allocator, keys, values, numValues, keyCallBacks, valueCallBacks);
			}
			return (MemorySegment) mh$.invokeExact(allocator, keys, values, numValues, keyCallBacks, valueCallBacks);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}

	private static class CFDataGetLength {
		public static final FunctionDescriptor DESC = FunctionDescriptor.of(MacSecurity.C_LONG, MacSecurity.C_POINTER);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("CFDataGetLength");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c : * extern CFIndex CFDataGetLength(CFDataRef theData)
	 * }
	 */
	public static FunctionDescriptor CFDataGetLength$descriptor() {
		return CFDataGetLength.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c : * extern CFIndex CFDataGetLength(CFDataRef theData)
	 * }
	 */
	public static MethodHandle CFDataGetLength$handle() {
		return CFDataGetLength.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c : * extern CFIndex CFDataGetLength(CFDataRef theData)
	 * }
	 */
	public static MemorySegment CFDataGetLength$address() {
		return CFDataGetLength.ADDR;
	}

	/**
	 * {@snippet lang = c : * extern CFIndex CFDataGetLength(CFDataRef theData)
	 * }
	 */
	public static long CFDataGetLength(MemorySegment theData) {
		var mh$ = CFDataGetLength.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("CFDataGetLength", theData);
			}
			return (long) mh$.invokeExact(theData);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}

	private static class CFDataGetBytePtr {
		public static final FunctionDescriptor DESC = FunctionDescriptor.of(MacSecurity.C_POINTER, MacSecurity.C_POINTER);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("CFDataGetBytePtr");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c : * extern const UInt8 *CFDataGetBytePtr(CFDataRef theData)
	 * }
	 */
	public static FunctionDescriptor CFDataGetBytePtr$descriptor() {
		return CFDataGetBytePtr.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c : * extern const UInt8 *CFDataGetBytePtr(CFDataRef theData)
	 * }
	 */
	public static MethodHandle CFDataGetBytePtr$handle() {
		return CFDataGetBytePtr.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c : * extern const UInt8 *CFDataGetBytePtr(CFDataRef theData)
	 * }
	 */
	public static MemorySegment CFDataGetBytePtr$address() {
		return CFDataGetBytePtr.ADDR;
	}

	/**
	 * {@snippet lang = c : * extern const UInt8 *CFDataGetBytePtr(CFDataRef theData)
	 * }
	 */
	public static MemorySegment CFDataGetBytePtr(MemorySegment theData) {
		var mh$ = CFDataGetBytePtr.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("CFDataGetBytePtr", theData);
			}
			return (MemorySegment) mh$.invokeExact(theData);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}

	private static class CFStringCreateWithCString {
		public static final FunctionDescriptor DESC = FunctionDescriptor.of(MacSecurity.C_POINTER, MacSecurity.C_POINTER,
				MacSecurity.C_POINTER, MacSecurity.C_INT);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("CFStringCreateWithCString");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c
	 * : * extern CFStringRef CFStringCreateWithCString(CFAllocatorRef alloc, const char *cStr, CFStringEncoding encoding)
	 * }
	 */
	public static FunctionDescriptor CFStringCreateWithCString$descriptor() {
		return CFStringCreateWithCString.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c
	 * : * extern CFStringRef CFStringCreateWithCString(CFAllocatorRef alloc, const char *cStr, CFStringEncoding encoding)
	 * }
	 */
	public static MethodHandle CFStringCreateWithCString$handle() {
		return CFStringCreateWithCString.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c
	 * : * extern CFStringRef CFStringCreateWithCString(CFAllocatorRef alloc, const char *cStr, CFStringEncoding encoding)
	 * }
	 */
	public static MemorySegment CFStringCreateWithCString$address() {
		return CFStringCreateWithCString.ADDR;
	}

	/**
	 * {@snippet lang = c
	 * : * extern CFStringRef CFStringCreateWithCString(CFAllocatorRef alloc, const char *cStr, CFStringEncoding encoding)
	 * }
	 */
	public static MemorySegment CFStringCreateWithCString(MemorySegment alloc, MemorySegment cStr, int encoding) {
		var mh$ = CFStringCreateWithCString.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("CFStringCreateWithCString", alloc, cStr, encoding);
			}
			return (MemorySegment) mh$.invokeExact(alloc, cStr, encoding);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}

	private static class kCFBooleanTrue$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kCFBooleanTrue").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFBooleanRef kCFBooleanTrue
	 * }
	 */
	public static AddressLayout kCFBooleanTrue$layout() {
		return kCFBooleanTrue$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFBooleanRef kCFBooleanTrue
	 * }
	 */
	public static MemorySegment kCFBooleanTrue$segment() {
		return kCFBooleanTrue$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFBooleanRef kCFBooleanTrue
	 * }
	 */
	public static MemorySegment kCFBooleanTrue() {
		return kCFBooleanTrue$constants.SEGMENT.get(kCFBooleanTrue$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFBooleanRef kCFBooleanTrue
	 * }
	 */
	public static void kCFBooleanTrue(MemorySegment varValue) {
		kCFBooleanTrue$constants.SEGMENT.set(kCFBooleanTrue$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecClass$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecClass").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClass
	 * }
	 */
	public static AddressLayout kSecClass$layout() {
		return kSecClass$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClass
	 * }
	 */
	public static MemorySegment kSecClass$segment() {
		return kSecClass$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClass
	 * }
	 */
	public static MemorySegment kSecClass() {
		return kSecClass$constants.SEGMENT.get(kSecClass$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClass
	 * }
	 */
	public static void kSecClass(MemorySegment varValue) {
		kSecClass$constants.SEGMENT.set(kSecClass$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecClassGenericPassword$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecClassGenericPassword").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClassGenericPassword
	 * }
	 */
	public static AddressLayout kSecClassGenericPassword$layout() {
		return kSecClassGenericPassword$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClassGenericPassword
	 * }
	 */
	public static MemorySegment kSecClassGenericPassword$segment() {
		return kSecClassGenericPassword$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClassGenericPassword
	 * }
	 */
	public static MemorySegment kSecClassGenericPassword() {
		return kSecClassGenericPassword$constants.SEGMENT.get(kSecClassGenericPassword$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecClassGenericPassword
	 * }
	 */
	public static void kSecClassGenericPassword(MemorySegment varValue) {
		kSecClassGenericPassword$constants.SEGMENT.set(kSecClassGenericPassword$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecAttrAccount$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecAttrAccount").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrAccount
	 * }
	 */
	public static AddressLayout kSecAttrAccount$layout() {
		return kSecAttrAccount$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrAccount
	 * }
	 */
	public static MemorySegment kSecAttrAccount$segment() {
		return kSecAttrAccount$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrAccount
	 * }
	 */
	public static MemorySegment kSecAttrAccount() {
		return kSecAttrAccount$constants.SEGMENT.get(kSecAttrAccount$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrAccount
	 * }
	 */
	public static void kSecAttrAccount(MemorySegment varValue) {
		kSecAttrAccount$constants.SEGMENT.set(kSecAttrAccount$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecAttrService$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecAttrService").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrService
	 * }
	 */
	public static AddressLayout kSecAttrService$layout() {
		return kSecAttrService$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrService
	 * }
	 */
	public static MemorySegment kSecAttrService$segment() {
		return kSecAttrService$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrService
	 * }
	 */
	public static MemorySegment kSecAttrService() {
		return kSecAttrService$constants.SEGMENT.get(kSecAttrService$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecAttrService
	 * }
	 */
	public static void kSecAttrService(MemorySegment varValue) {
		kSecAttrService$constants.SEGMENT.set(kSecAttrService$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecMatchLimit$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecMatchLimit").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimit
	 * }
	 */
	public static AddressLayout kSecMatchLimit$layout() {
		return kSecMatchLimit$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimit
	 * }
	 */
	public static MemorySegment kSecMatchLimit$segment() {
		return kSecMatchLimit$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimit
	 * }
	 */
	public static MemorySegment kSecMatchLimit() {
		return kSecMatchLimit$constants.SEGMENT.get(kSecMatchLimit$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimit
	 * }
	 */
	public static void kSecMatchLimit(MemorySegment varValue) {
		kSecMatchLimit$constants.SEGMENT.set(kSecMatchLimit$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecMatchLimitOne$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecMatchLimitOne").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimitOne
	 * }
	 */
	public static AddressLayout kSecMatchLimitOne$layout() {
		return kSecMatchLimitOne$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimitOne
	 * }
	 */
	public static MemorySegment kSecMatchLimitOne$segment() {
		return kSecMatchLimitOne$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimitOne
	 * }
	 */
	public static MemorySegment kSecMatchLimitOne() {
		return kSecMatchLimitOne$constants.SEGMENT.get(kSecMatchLimitOne$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecMatchLimitOne
	 * }
	 */
	public static void kSecMatchLimitOne(MemorySegment varValue) {
		kSecMatchLimitOne$constants.SEGMENT.set(kSecMatchLimitOne$constants.LAYOUT, 0L, varValue);
	}

	private static class kSecReturnData$constants {
		public static final AddressLayout LAYOUT = MacSecurity.C_POINTER;
		public static final MemorySegment SEGMENT = MacSecurity.findOrThrow("kSecReturnData").reinterpret(LAYOUT.byteSize());
	}

	/**
	 * Layout for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecReturnData
	 * }
	 */
	public static AddressLayout kSecReturnData$layout() {
		return kSecReturnData$constants.LAYOUT;
	}

	/**
	 * Segment for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecReturnData
	 * }
	 */
	public static MemorySegment kSecReturnData$segment() {
		return kSecReturnData$constants.SEGMENT;
	}

	/**
	 * Getter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecReturnData
	 * }
	 */
	public static MemorySegment kSecReturnData() {
		return kSecReturnData$constants.SEGMENT.get(kSecReturnData$constants.LAYOUT, 0L);
	}

	/**
	 * Setter for variable:
	 * {@snippet lang = c : * extern const CFStringRef  _Nonnull kSecReturnData
	 * }
	 */
	public static void kSecReturnData(MemorySegment varValue) {
		kSecReturnData$constants.SEGMENT.set(kSecReturnData$constants.LAYOUT, 0L, varValue);
	}

	private static class SecItemCopyMatching {
		public static final FunctionDescriptor DESC = FunctionDescriptor.of(MacSecurity.C_INT, MacSecurity.C_POINTER,
				MacSecurity.C_POINTER);

		public static final MemorySegment ADDR = MacSecurity.findOrThrow("SecItemCopyMatching");

		public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
	}

	/**
	 * Function descriptor for:
	 * {@snippet lang = c : * OSStatus SecItemCopyMatching(CFDictionaryRef  _Nonnull query, CFTypeRef  _Nullable * _Nullable result)
	 * }
	 */
	public static FunctionDescriptor SecItemCopyMatching$descriptor() {
		return SecItemCopyMatching.DESC;
	}

	/**
	 * Downcall method handle for:
	 * {@snippet lang = c : * OSStatus SecItemCopyMatching(CFDictionaryRef  _Nonnull query, CFTypeRef  _Nullable * _Nullable result)
	 * }
	 */
	public static MethodHandle SecItemCopyMatching$handle() {
		return SecItemCopyMatching.HANDLE;
	}

	/**
	 * Address for:
	 * {@snippet lang = c : * OSStatus SecItemCopyMatching(CFDictionaryRef  _Nonnull query, CFTypeRef  _Nullable * _Nullable result)
	 * }
	 */
	public static MemorySegment SecItemCopyMatching$address() {
		return SecItemCopyMatching.ADDR;
	}

	/**
	 * {@snippet lang = c : * OSStatus SecItemCopyMatching(CFDictionaryRef  _Nonnull query, CFTypeRef  _Nullable * _Nullable result)
	 * }
	 */
	public static int SecItemCopyMatching(MemorySegment query, MemorySegment result) {
		var mh$ = SecItemCopyMatching.HANDLE;
		try {
			if (TRACE_DOWNCALLS) {
				traceDowncall("SecItemCopyMatching", query, result);
			}
			return (int) mh$.invokeExact(query, result);
		} catch (Throwable ex$) {
			throw new AssertionError("should not reach here", ex$);
		}
	}
}
